### ISSUE TITLE
block-code defined but not referenced anywhere

### ISSUE THREAD

**Issue by kanru** [ingydotnet/swim-pgx#1]
Hi, I tried to implement a swim parser according to this spec, I found that `block-code` is defined but not used anywhere. Is it a TODO or left over?

**Comment by ingydotnet** [comment]
Fixed. Thanks.

Sorry for the late reply.

This is not a /spec/ it's a grammar for the Pegex parsing framework.

A fully working implementation is here:
- https://github.com/ingydotnet/pegex-pm
- https://metacpan.org/pod/Pegex

The implementation is Perl, but can easily be ported anywhere Pegex works. The
idea of Pegex is a programming language agnostic parsing framework (using regex
under the hood).

This took a while because I had some grammar fixes in another repo and needed
to get the new git-subrepo command working better:
- https://github.com/ingydotnet/git-subrepo#readme

If you want to chat about Swim or Pegex please join the #swimtext or #pegex
channels on irc.freenode.net.

Thanks again filing these issues.

**Comment by ingydotnet** [comment]
Sorry I meant that a fully working implementation is here:
- https://github.com/ingydotnet/swim-pm
- https://metacpan.org/pod/Swim
